package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.bean.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Jul 12 17:09:06 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Jul 12 17:09:06 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Jul 12 17:09:06 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Jul 12 17:09:06 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Jul 12 17:09:06 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Tue Jul 12 17:09:06 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * 查询账户是否存在
     * @param map 账户和密码
     * @return 成功后返回账户信息
     */
    User selectUserByActAndPwd(Map<String,Object> map);

    /**
     * 查询所有用户
     * @return
     */
    List<User>  selectUsersAll();
}
